# Generated by Django 6.0.3 on 2026-03-12 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('ticker', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('sector', models.CharField(blank=True, default='', max_length=100)),
                ('industry', models.CharField(blank=True, default='', max_length=200)),
            ],
            options={
                'verbose_name_plural': 'companies',
                'ordering': ['ticker'],
            },
        ),
        migrations.CreateModel(
            name='BenchmarkIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_symbol', models.CharField(max_length=20)),
                ('index_name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('close', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'benchmark indices',
                'ordering': ['index_symbol', 'date'],
                'indexes': [models.Index(fields=['index_symbol', 'date'], name='market_benc_index_s_05c7fb_idx'), models.Index(fields=['date'], name='market_benc_date_dae054_idx')],
                'unique_together': {('index_symbol', 'date')},
            },
        ),
        migrations.CreateModel(
            name='MarketCapRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('rank', models.IntegerField()),
                ('market_cap', models.FloatField(help_text='Market cap in USD')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to='market.company')),
            ],
            options={
                'ordering': ['year', 'rank'],
                'indexes': [models.Index(fields=['year', 'rank'], name='market_mark_year_df1722_idx'), models.Index(fields=['company', 'year'], name='market_mark_company_e2301b_idx')],
                'unique_together': {('company', 'year')},
            },
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('open', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
                ('volume', models.BigIntegerField()),
                ('adj_close', models.FloatField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='market.company')),
            ],
            options={
                'verbose_name_plural': 'price histories',
                'ordering': ['company', 'date'],
                'indexes': [models.Index(fields=['company', 'date'], name='market_pric_company_0027b3_idx'), models.Index(fields=['date'], name='market_pric_date_c97db2_idx')],
                'unique_together': {('company', 'date')},
            },
        ),
    ]
